name: CI/CD Pipeline
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
permissions:
  contents: read
  id-token: write  # Required for npm provenance

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.1

      - name: Cache pnpm
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Biome
        run: pnpm add -g @biomejs/biome

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Generate coverage report
        run: pnpm coverage

      - name: Publish code coverage report
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: pnpm publish --provenance --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
